# -*- coding: utf-8 -*-
"""
/***************************************************************************
 group10Dialog
                                 A QGIS plugin
 group10
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-12-24
        git sha              : $Format:%H$
        copyright            : (C) 2021 by group10
        email                : emreabaogluu@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""


